phys2bids/interfaces/txt.py, phys2bids/phys2bids.py, phys2bids/physio_obj.py, phys2bids/utils.py
close #48 
Hi guys, I implemented txt support for labchart files, could you review my code? no rush.
Cheers,
Vicente
=> Adding txt support for labchart 

phys2bids/physio_obj.py
Closes #88 
- This modifies both the `BlueprintInput` and `BlueprintOutput` classes so that the `ch_amount` property is now a @property-decorated method. This alleviates the need to manually update it in other methods that might modify the `timeseries` property (on which `ch_amount` depends).
=> [REF] Use @property for ch_amount in physio_obj

phys2bids/interfaces/txt.py
Closes #
- Now the sampling number is in the header not in the channel_list
-
-
=> put number of samples in the header instead of the channel_list

phys2bids/interfaces/txt.py
- Solves reading problem when ``txt`` file has a line with extra tabs that creates null elements '', no instead of being an if, it's a while loop, therefore if there is more than one extra tab it deletes them all 
- channel_list variables is a list of list of samplesxchannels and we want the transpose: channelsxsamples. Now we use  ``timeseries=list(map(list, zip(*channel_list)))`` instead of ``timeseries = np.matrix(channel_list).T.tolist()``. This affects acqknowledge and labchart files.
=> solve list transpose that was buggy and problem with lines with extra blank tabs in reading

.travis.yml, phys2bids/interfaces/acq.py, phys2bids/tests/conftest.py, phys2bids/tests/test_acq.py, phys2bids/tests/test_integration.py, phys2bids/tests/test_phys2bids.py, phys2bids/tests/test_txt.py, phys2bids/tests/test_utils.py, phys2bids/tests/test_viz.py, phys2bids/viz.py, setup.cfg
Closes #179 
This PR makes (most) of the changes I described in #179 to demonstrate how it would change the test suite. It's a rather large PR (very sorry), largely because this is a pretty dramatic overhaul to the way testing had been set up. It's my hope that moving forward from this would reduce boilerplate code for tests (e.g., fetching new test data files) and streamline things.
- Removes `wget` dependency and consolidates fetching of all test data to [`phys2bids/tests/conftest.py`](https://docs.pytest.org/en/latest/fixture.html#conftest-py-sharing-fixture-functions)
- Modifies all test data downloads to use `pytest`'s temporary directory rather than going to `phys2bids/tests/data` to avoid modifying local git repos when testing locally
- Updates all tests to use new test data …
=> [TEST] Consolidates / updates test suite

phys2bids/phys2bids.py
Closes #184 
- timeseries matrix gets transposed during its export, to be BIDS compliant.
(thanks to @sangfrois for pointing it out)
=> Quick fix for #184

phys2bids/phys2bids.py, phys2bids/physio_obj.py, phys2bids/tests/test_physio_obj.py
Closes #184 better than #187 
- Instead of a final transposition of the `timeseries` attribute of the `BlueprintOuput` during export, the object is initialised BIDS compliant.
=> Improve code compliance to BIDS in BlueprintOputput

phys2bids/phys2bids.py, phys2bids/tests/test_viz.py, phys2bids/viz.py
Closes #188 
- Update ``viz.trigger_plot ``docstring
- Change ``viz,plot_all`` inputs so instead of phys_in we enter all the parameters in a separated way
- Update ``viz.plot_all`` docstring after this
=> Update viz.py docstrings and Inputs 

docs/bestpractice.rst
Closes #99 addresses #12
- Merging the changes and updates for the documentation on best practices for collecting physiological data
-
-
=> Add section on "Best Practices for Phys Data Collection"

.azure-pipelines/windows.yml
Closes #215 
- Adds `failOnStderr` entry to YAML for running the tests to, hopefully, fail when there are errors
Not sure if this will _actually_ fix things given that they seem to magically be working again, but will see how things go with this PR. May purposefully break something to see if I can reproduce the errors we were seeing before, but will let this run through once, first!
=> Fix azure pipelines non-failure bug

phys2bids/phys2bids.py, phys2bids/physio_obj.py, phys2bids/tests/test_integration.py
Closes #26 
- Any print of a float should have max 4 decimals. 
-  Currently, I added some code to print out _start_time_ with 4 decimals places in both the log and the json file. This was just something I quickly tried - Is this the kind of thing we want? Or will I need to make this more generalised and make a function that defines how any float is printed? 
- I am not sure how I approach writing the unit test.
=> Print float to max 4 decimal places

docs/bids.rst, docs/index.rst
Closes #202 
This is a *very* rough first pass but I figured opening a PR asap was ideal since we're aiming to get things done by Thursday 💪 Happy to merge this with other efforts if those were underway (though I didn't see anything on GitHub, I recognize people could have been working locally).
- Adds page to the documentation describing what BIDS is, why we're using it, and (briefly) the role of `phys2bids` in `physiopy`
=> Adds "Why BIDS?" page to the documentation

.gitignore, docs/api.rst
Closes #??
- Adds info to reference API
What other functions /  classes should be added to the API? Happy to add whatever but I don't think _everything_ needs to be on it.
=> Update reference API

.travis.yml
#181 didn't go as expected.
This *should* fix it.
- Add checks on branches and correct them
- Add messages to the user
=> Fix TravisCI configuration for auto

phys2bids/bids.py, phys2bids/cli/run.py, phys2bids/heuristics/participant.yml, phys2bids/phys2bids.py, phys2bids/tests/test_integration.py, phys2bids/utils.py, requirements.txt, setup.cfg
Partly closes #242 and #185 
- Generate participants.tsv if it doesn't exist already.
=> Generate participants.tsv if it doesn't exist or update it if subject is missing in the file

phys2bids/cli/run.py, phys2bids/phys2bids.py, phys2bids/tests/test_integration.py, phys2bids/tests/test_viz.py, phys2bids/viz.py
- Create extra folder under the output dir
- Eliminate channels plot path output option and output channel plot always here, channel plot not optional anymore
- Eliminate trigger plot path output option and output channel plot always here, channel plot not optional anymore
- Change logger file output folder to extra
- Same with subject log file
=> Create bids_ignore directory and redirect channels plot, trigger plot, logger output and subject log file to this directory

phys2bids/bids.py, phys2bids/phys2bids.py, phys2bids/tests/test_bids.py
Closes #243 
- Generate dataset_description.json if it doesn't exist already.
- Generate README if it doesn't exist already.
=> Generate dataset_description.json and README.md when they do not exist and update the json file when the subject is missing

docs/index.rst, phys2bids/due.py, phys2bids/phys2bids.py, setup.cfg
Closes #248.
- Add `duecredit` as an optional dependency.
- Add `duecredit` stub file, which is necessary to prevent errors when duecredit is not installed.
- Add citations for phys2bids Zenodo and BIDS paper as decorators to main workflow.
=> Add duecredit to handle citations

phys2bids/phys2bids.py, phys2bids/tests/test_integration.py
Closes #256 
- Create  ``code/coversion`` folder
- generating log, trigger_plot, channel_plot, heuristic file and yam file to ``code/coversion`` folder
- create new file ``call.sh`` that contains the original call to phys2bids
=> Create folder code/conversion to store trigger and channel plots, yaml and heuristic files and the call.sh file

phys2bids/tests/test_bids.py, phys2bids/tests/test_utils.py
Adresses #252 by testing new functions in ``bids.py`` and ``utils.py``
- testing ``append_list_as_row()``
- testing ``participants_file()``
This would lead to increased coverage 👍
=> Add unit tests for participants_file and append_list_as_row

phys2bids/heuristics/heur_test_acq.py, phys2bids/heuristics/heur_test_multifreq.py, phys2bids/tests/test_integration.py
Closes #258
- Remove redundant integration tests to gain in testing speed.
=> Remove redundant integration tests

phys2bids/tests/conftest.py, phys2bids/tests/test_integration.py
I does not close the issue on adding tests for the multi run pipeline as we still have to add unit tests for `split4phys.py`. I will tackle that in another PR if no one else does it before. The main objective of this PR is to get our code coverage above 90% for OHBM.
- The title says it all.
=> Add integration test for the multi run pipeline

phys2bids/cli/run.py, phys2bids/interfaces/acq.py, phys2bids/phys2bids.py
Closes #272, although the fixed problem is not the same - still, thanks @tsalo!
Turns out the algorithm was meant to extract the channel _after_ the one of the trigger since we modified phys2bids to have `-chtrig` human-friendly (rather than pythonic). 
- the `chtrig` index is lowered by one in place when extracting the timeseries from the trigger channel.
- the docstring now indicate that chtrig is meant to represent an index starting from 1.
=> Correct trigger channel indexing while reading AcqKnowledge files.

phys2bids/__init__.py, phys2bids/_version.py, phys2bids/bids.py, phys2bids/cli/__init__.py, phys2bids/due.py, phys2bids/interfaces/__init__.py, phys2bids/interfaces/txt.py, phys2bids/slice4phys.py, phys2bids/utils.py, phys2bids/viz.py, setup.cfg
Closes #293
- Fix linting errors around the entire package.
=> Fix linting errors

README.md, docs/index.rst
Closes #296
- Change link to Travis CI for the link to CircleCI to display correct build shield.
=> Change build shield from Travis to CircleCI

README.md
Closes none.
- Add link to developer calls Google Calendar to our README.
=> Add link to Google Calendar

phys2bids/interfaces/txt.py, phys2bids/tests/test_txt.py
Closes #273
quick, very neat refactoring to lower the chances of confusion while reading the code:
- Delete [line 322](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L322)
- Remove chtrig from [this definition's argoments](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L254), since it's not used in the definition itself.
- Change `chtrig +1` in [this line](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L152) and in [this line](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L251) into `chtrig` only.
- Add explanation of `chtrig` …
=> Refractor txt.py chtrig parameter to improve code readability

docs/contributorfile.rst
Closes #
- Updates all Travis CI mentions to CircleCI.
=> Update documentation to reflect change from Travis CI to CircleCI

.all-contributorsrc, .autorc, .github/workflows/auto-release.yml, README.md, codecov.yml, docs/index.rst
Closes #311 and closes #239
Second attempt to integrate `auto` as a workflow, this time as a GitHub action. IF this works, we have a great automated workflow from PR merge to Pypi package (with the other workflow).
- Add `.autorc` configuration file
- Add github workflow that * should * retrieve the latest version of auto (might not be elegant) and then run it 
- Add a couple of badges.
I can't wait to see if this works. So exciting!
@hipstersmoothie, could you please have a look at this PR?
@yarikoptic and @jwodder, you could have a look into this too - if you implemented a different solution I'd like to compare them, and otherwise if this works it should help you with datalad/datalad#4999 and dandi/dandi-cli#252!
=> Setup auto release workflow

docs/installation.rst, setup.cfg
Closes none
While running a test locally, I realised that we need to force the version of PyYAML to be 5.1 or above for our scripts to work: https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader
- Update PyYAML requirements
- Update requirements in documentation
=> Update PyYAML minimal requirements to avoid "FullLoader" attribute errors.

.circleci/artifact_path
References #300, but probably doesn't fix it.
- Fix a typo in the artifact path used to build the path for the `build_docs_artifact` CI step. This should fix the link for PRs from forks _without_ CircleCI running.
=> Fix typo in artifact_path

phys2bids/tests/test_utils.py, phys2bids/utils.py
#Closes #336 and #closes #337 
- Removes the in-house built function to move the files from the Utilities collection;
- Removes the test for in-house built function to move the files from the Unit test for Utilities collection.
=> Remove utils.move_file function as it is no longer used in the toolbox

phys2bids/bids.py, phys2bids/phys2bids.py, phys2bids/tests/test_utils.py, phys2bids/utils.py
Closes #332 
- Rename the function
- Update tests
- Update all uses of the function throughout the package
Didn't update the API page of docs since apparently there isn't one for utils
=> Rename function `utils.writefile` to `utils.write_file` to respect style

phys2bids/bids.py, phys2bids/phys2bids.py, phys2bids/tests/test_utils.py, phys2bids/utils.py
Closes #334 
-Remove the function and the associated tests
-Replace the function call throughout the package
=> Replace utils.path_exists_or_make_it() with os.makedirs()

.mailmap
.mailmap is mechanism to properly account for contributors using different git configuration "ids".  
<details>
<summary>output on master master</summary> 
```shell
$> git shortlog -sn | nl
1	   446	Stefano Moia
2	   415	vinferrer
3	   231	Vicente Ferrer
4	   215	smoia
5	   112	François Lespinasse
6	   101	Eneko
7	    74	Eneko Uruñuela
8	    74	eurunuela
9	    54	Ross Markello
10	    49	Rachael Stickland
11	    44	allcontributors[bot]
12	    19	Apoorva Ayyagari
13	     6	Taylor Salo
14	     4	Daniel Alcalá
15	     4	Merel van der Thiel
16	     4	Vittorio Iacovella
17	     3	RayStick
18	     3	kristinazvolanek
19	     2	BrightMG
20	     2	Inés Chavarría
21	     2	Molly Bright
22	     1	Daniel Alcalá López
23	     1	Katie Bottenhorn
24	     1	Kristina Zvolanek
25	     1	Victor
26	     1 …
```
=> Add .mailmap to improve `git shortlog -sn` output

.ci/w_python_36, .ci/w_python_37, .ci/w_python_38, .ci/w_python_39, .cirrus.yml
Closes Nothing
I realised that even though the windows tests were passing, there where errors with ``pip`` that should trigger the failure. After speaking with the cirrus support (https://github.com/cirruslabs/cirrus-ci-docs/issues/765) we realised that using ``powershell`` was the problem. Therefore I proposed to apply this tiny changes to the windows tests so they work and trigger failure when something breaks.
- Stop using ``powershell`` as windows interpreter
- Migrate some libraries installation to the docker build ( ``numpy matplotlib Cython PyYAML h5py scipy``)
- Sorry for not adding this to the previous PR
=> Stop using powershell as windows interpreter

.cirrus.yml, Makefile
Closes Nothing
- Now if you access the build docs job page you can check and download the html/docs when they finished. This is temporal, if we can use this: https://docs.readthedocs.io/en/stable/pull-requests.html much better but @smoia has to look into it
- Now if you access the integration  jobs  pages you can check and download the results from integration jobs  when they are finished
-
=> Provide the outcome of integration and documentation tests as downloadable artifacts from each Cirrus CI test page

phys2bids/phys2bids.py, phys2bids/tests/test_phys2bids.py
Closes #389 
- Change chtrig check value from 1 to 0 (phys2bids.py)
- Modify chtrig test to check that a negative value raises the exception (test_phys2bids.py)
=> correct chtrig check in phys2bids main workflow

phys2bids/phys2bids.py, phys2bids/physio_obj.py, phys2bids/tests/test_phys2bids.py, phys2bids/tests/test_physio_obj.py
Related to #204 and #386. 
This implements a time-domain detection of the trigger when the text-matching detection fails.
- **Added a time-domain detection of the trigger**
The implementation computes a metric measuring how much each channel differs from a binary signal. The metric is computed as the average distance from each point to the closest limit of the signal (min or max). 
More "binary-like" signals like the trigger should have most of the points closer to either signal limit resulting on a smaller metric. Assuming this,  the trigger is detected as the channel that minimizes the metric.
Changes regarding the chtrig=0 are part of #390 (hope it is not confusing).
=> Add additional automatic detection of the trigger based on time-domain analysis

phys2bids/phys2bids.py
A very broad Exception was raised, which makes it hard to catch. Now two kind of exceptions are raised, 1) RuntimeError for invalid input data and 2) NotImplementedError if that is the case (before the broad 'Exception' base-class was raised)
raise Exception() -> raise RuntimeError / NotImplementedError
=> Define previously unspecified Exceptions in the main workflow

.cirrus.yml
Closes #411 
- Use `apt-get install build-essential` rather than `apt-get install make`
-
-
=> Fix testing enviroment by using `apt-get install build-essential` rather than `apt-get install make`

phys2bids/phys2bids.py
Closes #437 
Fix the loop to delete information at indexes not included in specified channel selections by ignoring channel 0.
-
-
-
=> Fix channel selection to not remove "time channel" 

.circleci/config.yml, .pre-commit-config.yaml, docs/conf.py, phys2bids/__init__.py, phys2bids/_version.py, phys2bids/bids.py, phys2bids/cli/run.py, phys2bids/due.py, phys2bids/heuristics/heur_euskalibur.py, phys2bids/heuristics/heur_test_acq.py, phys2bids/heuristics/heur_test_multifreq.py, phys2bids/heuristics/heur_tutorial.py, phys2bids/io.py, phys2bids/phys2bids.py, phys2bids/physio_obj.py, phys2bids/slice4phys.py, phys2bids/tests/conftest.py, phys2bids/tests/test_bids.py, phys2bids/tests/test_integration.py, phys2bids/tests/test_io.py, phys2bids/tests/test_phys2bids.py, phys2bids/tests/test_physio_obj.py, phys2bids/tests/test_utils.py, phys2bids/tests/test_viz.py, phys2bids/utils.py, phys2bids/viz.py, pyproject.toml, setup.cfg, setup.py, versioneer.py
Closes #324. 
- Change `flake8` dependency to `flake8-black`. Calling `flake8` in the CI will use `flake8-black` automatically.
- Ignore E203 (whitespace before ':'), which `flake8` flags, but which is actually not PEP8 compliant. See [here](https://black.readthedocs.io/en/stable/compatible_configs.html#flake8) for an explanation.
=> Adopt Black and isort

phys2bids/io.py, phys2bids/tests/conftest.py, phys2bids/tests/test_io.py, setup.cfg
Addresses #405.
The current implementation uses the official API, `sonpy`, from CED. `sonpy` is closed sourced.
**In order to support `sonpy`, the minimal python version should be 3.7.** Hence I will mark this as part of the major release.
The scanner volume trigger in the test file was stored as a "marker" channel. The `sonpy` API returns time points of markers, rather than a timeseries. The module I wrote has been tested locally. I cannot run the full test due to bandwidth and data limit. Will check if this breaks other tests.
- Add `phys2bids.io.load_smr`
=> Add support for Spike2 files

phys2bids/physio_obj.py, phys2bids/tests/test_viz.py, phys2bids/viz.py, requirements.txt
cutting acq files into runs lead to very unreasonably large memory usage, and long runtime.
After memory and time profiling here are the proposed changes.
I ran the test locally and some crashed but do not seem related to my changes. I fixed one of the fail test by adding the missing requirements. 
- properly close matplotlib figures after rendering/saving to avoid clogging memory
- replace loop-based trigger counting with a more (100-fold) efficient numpy-based one. 
- fix requirements to have some failing test passing
=> Improve performance by using numpy for trigger detection and closing matplotlib figures to avoid memleaks.

.pre-commit-config.yaml, .readthedocs.yml, setup.cfg
=> Fix readthedocs and update configuration

README.md
I was reading the README file and noticed a typo, so I corrected it. Then also made a few minor formatting improvements. I did them each as separate commits if we only want to accept some of them.
1.  I corrected a spelling mistake (_Subsistems -> Subsystems_)
2.  The line that starts _"We want to offer as much support as possible ..."_ was on the same line as the GE bullet point but it looked like it was meant to be on a separate line
3.   Some suggested re-wording to the _'Tested OSs'_ section - there were no mistakes here though, so just improvements.
=> Correct typos and formatting in README
