physiopy/phys2bids

README.md
Checked repo in virtual environment, these are the minimum versions that work.
=> Updated versions required

README.md, phys2bids/phys2bids.py, phys2bids/tests/data/README.md
Relates to Issues #31 
I added the full boilerplate to the README
I added a README file in tests/data containing the full boilerplate 
I added the license information to the phys2bids/phys2bids.py code   only
=> (Some) License Information Added

requirements.txt, setup.cfg
Updated requirements with bioread version
=> Requirements

phys2bids/heuristics/heur_ex.py, phys2bids/physio_obj.py
close #51 
I adressed issue #51 in this pull request, now the method rename_channels works correctly
=>  Solving issue #51

phys2bids/phys2bids.py, phys2bids/physio_obj.py
If the option ses or sub are used, the trigger plot name reflects it.
=> Improved trigger output

phys2bids/tests/test_phys2bids.py, phys2bids/tests/test_physio_obj.py, phys2bids/tests/test_utils.py
I'm creating this new draft PR as suggested by @smoia.
=> [TST/WIP] Adds unit tests

phys2bids/heuristics/heur.py, phys2bids/heuristics/heur_ex.py
Very quick PR to fix Errors in linting for heuristics and `phys2bids.py`
=> Fixed linting

phys2bids/cli/run.py, phys2bids/phys2bids.py
When doing user testing, I first interpreted 'time points' to mean samples in my data, and got errors with using phys2bids because of that. I realized that it meant TRs fairly quickly, but I've suggested a small change to the wording in the help text to help that be clearer to people
=> Changes to get_parser 

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_BUGS.md, .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_GENERAL.md
- Moves issue templates into ISSUE_TEMPLATES folder.
=> [FIX] Moved issue templates into folder

.github/PULL_REQUEST_TEMPLATE.md
- It rephrases the issue closing sentence at the beginning of the template. I believe "Closes #XX" is clearer than "Fixes #XX".
=> [ENH] Rephrases PR template

phys2bids/cli/run.py, phys2bids/phys2bids.py, phys2bids/physio_obj.py
Partially fixes #92
- Fixes linting errors in `physio_obj.py`
- Fixes linting errors in `cli/run.py`
=> [FIX] Fixes linting errors

docs/contributing.rst, docs/installation.rst
=> Document fix for #121

docs/bestpractice.rst
=> [DOC] populated doc with outline and initial info

phys2bids/interfaces/txt.py, phys2bids/phys2bids.py
Closes #40 
Sorry people, but this part is raising the last error in unit testing.
- Changed strings concatenations into f-strings
- Changed path expression to use os.path.join
=> Refactor use_heuristics for strings and paths

phys2bids/tests/test_acq.py, phys2bids/tests/test_utils.py
Closes #
- Add tests for acq.py
=> Started working on acq tests

phys2bids/phys2bids.py
=> Added empty line in summary

docs/contributing.rst, docs/contributorfile.rst
=> Corrected links

phys2bids/phys2bids.py
Closes #
- Moves outputdir check and creation at the very beginning to avoid bug with logger creation
=> Change order of output folder existence check and creation before logger init

phys2bids/phys2bids.py
Closes #163 
- Change for loop that separates phys_in object in two objects by frequency  and saves then in phys_out dict
- The functionality is the same but now the code doesn't crush
=> fix frequency separation

phys2bids/phys2bids.py, phys2bids/viz.py
Closes #
- Adjusts main function for easier testing and usage of phys2bids from inside python.
- Basically, the main function called phys2bids now receives arguments from the parser instead of calling the parser itself.
=> Adjusts main function for easier testing and usage of phys2bids from inside python

docs/bestpractice.rst
Address #12 and closed issue #99 
- Formatted bulleted lists
- Corrected References hyperlink target
=> Fix formatting on "Best Practices for Phys Data Collection"

.travis.yml
#181 went as expected and didn't work out at the first attempt (obv).
Trying again.
-
-
-
=> Check branch in travisCI

.travis.yml
=> Add required token for Travis to run auto

phys2bids/tests/conftest.py, phys2bids/tests/test_integration.py, phys2bids/tests/test_txt.py
Co-authored-by: Rachael Stickland <50215726+RayStick@users.noreply.github.com>
Closes #221 and fixes #226.
Proposed Changes:
- Testing uses trimmed files to reduce computation time.
=> Update testing to use short files.

phys2bids/tests/test_integration.py
Closes nothing.
It's just a little lintering (I know Travis isn't working today, but let's still check the linter test, since we don't have it in Azure), while removing unused imports.
In addition, instead of importing `os` or its modules twice, it's importing `remove` and the three functions that we use from `path`.
I know this is not standard `os` import (@rmarkello you know better than us), but I think it's a bit better rather than importing os twice using similar modules, if we want a solution that saves digits.
I'd prefer to stick with `os.path.function` since it's easier to read, but if we want shorter solutions, at least it's a tiny bit clearer.
- Change `os` and `os.path` import
- Remove csv import
- General linter
=> Change os path import and linter

.github/workflows/python-publish.yml
Closes #
- Add pip workflow packaging
=> Automate python packaging

.github/workflows/auto-release.yml
Closes none
- reduce verbose in auto workflow by one
- Also tests auto release
=> Reduce `auto` verbosity

.autorc
=> Add label colours to set auto labels

.zenodo.json, README.md
- Update zenodo information in README
=> Update zenodo info

README.md, docs/index.rst
- Update badges in README and documentation
- A couple of other tweaks to update documentation
=> Update badges in README and documentation

.autorc, .github/workflows/auto-release.yml
- Use `shipit` instead of `release`
- Remove `prerelease` flag in auto settings
=> Fix auto release workflow settings

CHANGELOG.md, docs/contributing.rst, docs/installation.rst
Closes #319 
- Adds windows installation
- Adds pytest check and upstream setup for developers
=> Add Windows installation to the documentation

phys2bids/bids.py, phys2bids/phys2bids.py, phys2bids/tests/test_utils.py, phys2bids/utils.py
Closes #333 
-Rename the function
-Update tests
-Update all uses of the function throughout the package
=> Rename utils.writejson() to utils.write_json()

.github/PULL_REQUEST_TEMPLATE.md
Closes #
- Add more change type options in the PR template
-
-
=> Add more "change type" options

.circleci/config.yml
Closes none.
I found a tiny error in our testing configuration file. We were referencing a conda environment that did not exist. Good thing we created our own when that one didn't exist.
- Correctly check if our conda environment has already been created.
=> Fix call to conda environment reference in the test configuration file

phys2bids/phys2bids.py
Closes #265 
- Added a 0 in the plot_fileprefix string so #265 is corrected
-
-
=> Add 0 before run number to multi-run trigger plot file name

.circleci/config.yml
=> Correct BIDS validation test names

docs/howto.rst, docs/installation.rst
Closes  #210 
Small clarification of the documentation.
installation.rst
- Clarify the difference between installation with and without pip
- Clarify the installation steps
- Correct setup.py installation command
howto.rst
- Add phys2bids -h description as well as a link to the command line usage page.
=> Clarify installation instructions and tutorial

docs/howto.rst, phys2bids/physio_obj.py
Closes #211 
- Trigger threshold is now defined as the mean value of the trigger channel across time
- Logic: if trigger channel is binary (or roughly binary), the "on" state is always greater than the mean and the "off" state is always less than the mean
=> Update trigger threshold guess estimation to mean of trigger channel

.all-contributorsrc
=> Add @drombas as contributor

phys2bids/slice4phys.py
=> Prevent slicing from terminating program if end of last slice is above maximum timepoints.

phys2bids/physio_obj.py, phys2bids/viz.py
=> Fix trigger plots when trigger has different sampling than time

docs/api.rst, phys2bids/io.py
=> Fix documentation indexing

phys2bids/phys2bids.py
Closes none but references #431
This PR Fixes the use of trigger indexes.
-
-
-
=>  Fix trigger index update on channel subset selection (`-chsel`)

docs/api.rst, docs/howto.rst, docs/index.rst, phys2bids/io.py
Minor changes to the documentation were made to introduce the additional GE scanner physiological file functionality. 
That GE file functionality now exists is stated and some specific instructions were added to the "how to". 
The API section was also updated to include the ``load_gep`` function that loads in GE files.
=> Update documentation to include GE file functionality

.codespellrc, .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_FEATURE_REQUEST.md, .github/workflows/codespell.yml, .gitignore, CHANGELOG.md, phys2bids/_version.py, phys2bids/bids.py, phys2bids/cli/run.py, phys2bids/io.py, phys2bids/phys2bids.py, phys2bids/physio_obj.py, phys2bids/slice4phys.py, phys2bids/tests/conftest.py, phys2bids/tests/test_io.py, phys2bids/tests/test_utils.py, phys2bids/utils.py, phys2bids/viz.py
One decision was "in the code" - please check commit 3e8f68ebc6a7df39931560a765afd830ded83995
=> Codespell the code, add configuration and workflow for it so no typo sneaks in

setup.cfg
=> Remove wrong version of exclusion strings

README.md, docs/index.rst
=> Update supported file list

setup.cfg
- In `setup.cfg`, the `match` and `match_dir` flags of `pydocstyle` had a typo, which is fixed
=> Fix pydocstyle usage in setup.cfg

README.md
When you clicked on the contributor badge at the top of the README it did not jump to the contributor table at the bottom of the README as intended. This is because the hidden text chunk about the Hackathon was not closed
- Close the hidden text by adding `-->`
- Corrected the title for the link text `(#contributors-)`
=> Fix bug in README.md titles and links

.github/config.yml
Closes #
- @me-pic same change as in the other PRs
=> Update welcome bot text
